name = "shr-webhook"
main = "src/index.js"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[vars]
SUPABASE_URL = "https://htzadzpckcpdrmpjvaut.supabase.co"
DEFAULT_USER_ID = "VrMwzeSceqWeXVQOrm8kpu4uVR33"
HIGH_SHIN_API_BASE = "https://high-shin.shia2n.jp"
NAOKI_NOTIFY_EMAIL = "gameister1@gmail.com"
RESEND_FROM_EMAIL = "noreply@notify.shia2n.jp"

[triggers]
crons = ["0 0 * * *"]
